Repository SolarArbiter/solarforecastarbiter-api, pull requests merged in 2020-06, with the labels that each got.

#247 Limit data requests
  datastore/migrations/0051_reference_jobs.up.sql
  sfa_api/aggregates.py
  sfa_api/config.py
  sfa_api/conftest.py
  sfa_api/forecasts.py
  sfa_api/observations.py
  sfa_api/schema.py
  sfa_api/spec.py
  sfa_api/tests/test_aggregates.py
  sfa_api/tests/test_api.py
  sfa_api/tests/test_cdf_forecast.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
  sfa_api/tests/test_schema.py
  sfa_api/utils/request_handling.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_request_handling.py
Labels: bug, database, enhancement

#249 make sure start,end are localized before comparing
  sfa_api/tests/test_aggregates.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
  sfa_api/utils/request_handling.py
  sfa_api/utils/tests/test_request_handling.py
Labels: bug

#254 support for climate zones
  datastore/conf/testing.cnf
  datastore/docker-compose.yml
  datastore/migrations/0041_climate_zone_support.down.sql
  datastore/migrations/0041_climate_zone_support.up.sql
  datastore/migrations/0042_climate_zone_insert.up.sql
  datastore/tests/conftest.py
  datastore/tests/test_deletes.py
  datastore/tests/test_inserts.py
  datastore/tests/test_list.py
  datastore/tests/test_other.py
  datastore/tests/test_reads.py
  sfa_api/__init__.py
  sfa_api/conftest.py
  sfa_api/schema.py
  sfa_api/sites.py
  sfa_api/spec.py
  sfa_api/tests/test_sites.py
  sfa_api/tests/test_zones.py
  sfa_api/utils/request_handling.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_request_handling.py
  sfa_api/utils/tests/test_storage_interface.py
  sfa_api/utils/url_converters.py
  sfa_api/zones.py
Labels: database, enhancement

#257 use new observation validation function
  datastore/migrations/0051_reference_jobs.up.sql
  sfa_api/jobs.py
  sfa_api/observations.py
  sfa_api/tests/test_jobs.py
Labels: enhancement

#261 Enforce max content length
  sfa_api/aggregates.py
  sfa_api/error_handlers.py
  sfa_api/forecasts.py
  sfa_api/observations.py
  sfa_api/spec.py
  sfa_api/tests/test_cdf_forecast.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
  sfa_api/utils/request_handling.py
  sfa_api/utils/tests/test_request_handling.py
Labels: bug

#262 Add Cost to schema
  sfa_api/reports.py
  sfa_api/schema.py
  sfa_api/spec.py
  sfa_api/tests/test_reports.py
  sfa_api/utils/storage_interface.py
Labels: enhancement

#265 add forecast fill to report schema
  sfa_api/schema.py
  sfa_api/spec.py
  sfa_api/tests/test_reports.py
Labels: enhancement

#268 Allow posting of report values for CDF single objects
  datastore/migrations/0045_cdf_report_objects.down.sql
  datastore/migrations/0045_cdf_report_objects.up.sql
  datastore/tests/conftest.py
  datastore/tests/test_authorization.py
  datastore/tests/test_deletes.py
  datastore/tests/test_inserts.py
  datastore/tests/test_reads.py
  sfa_api/conftest.py
  sfa_api/tests/test_reports.py
Labels: database
