Repository SolarArbiter/solarforecastarbiter-api, pull requests merged in 2020-11, with the labels that each got.

#299 Remove report values not present in a raw_report update
  datastore/migrations/0053_remove_old_report_obj.down.sql
  datastore/migrations/0053_remove_old_report_obj.up.sql
  datastore/tests/test_inserts.py
  sfa_api/conftest.py
  sfa_api/reports.py
  sfa_api/tests/test_reports.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_storage_interface.py
Labels: bug, database

#305 Return error when empty data is posted.
  sfa_api/tests/test_cdf_forecast.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
  sfa_api/utils/request_handling.py
Labels: bug

#306 Add api auth examples and post examples
  datastore/docker-compose.yml
  sfa_api/spec.py
  sfa_api/utils/auth.py
Labels: enhancement

#307 test \ufeff in csv and add ref aggregate permissions
  datastore/migrations/0054_aggregate_permissions.down.sql
  datastore/migrations/0054_aggregate_permissions.up.sql
  sfa_api/utils/request_handling.py
  sfa_api/utils/tests/test_request_handling.py
Labels: bug, database, enhancement
