Repository SolarArbiter/solarforecastarbiter-api, pull requests merged in 2020-10, with the labels that each got.

#282 Adjust deletion procedures and add create_user to admincli
  datastore/migrations/0047_delete_updates.down.sql
  datastore/migrations/0047_delete_updates.up.sql
  datastore/tests/test_admin_procedures.py
  datastore/tests/test_deletes.py
  datastore/tests/test_inserts.py
  sfa_api/admincli.py
  sfa_api/tests/rbac/test_permissions.py
  sfa_api/tests/test_admincli.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_storage_interface.py
Labels: database

#283 adjust read values allowed on a different object type
  datastore/migrations/0048_updated_read_values.down.sql
  datastore/migrations/0048_updated_read_values.up.sql
  datastore/tests/test_reads.py
  sfa_api/tests/test_cdf_forecast.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
Labels: bug, database

#284 list all users for admincli at once
  sfa_api/tests/rbac/test_users.py
  sfa_api/users.py
  sfa_api/utils/auth0_info.py
  sfa_api/utils/tests/test_auth0_info.py
Labels: enhancement

#288 update api docs and fix openapi spec
  sfa_api/aggregates.py
  sfa_api/forecasts.py
  sfa_api/observations.py
  sfa_api/permissions.py
  sfa_api/schema.py
  sfa_api/spec.py
  sfa_api/tests/test_schema.py
  sfa_api/users.py
  sfa_api/utils/storage_interface.py
  sfa_api/zones.py
Labels: enhancement

#286 allow updates to some metadata
  datastore/docker-compose.yml
  datastore/migrations/0049_test_perms.up.sql
  datastore/migrations/0049_update_metadata.down.sql
  datastore/migrations/0049_update_metadata.up.sql
  datastore/migrations/0059_test_perms.down.sql
  datastore/migrations/0059_test_perms.up.sql
  datastore/migrations/0060_remove_admin_permissions.up.sql
  datastore/migrations/0061_reference_jobs.down.sql
  datastore/migrations/0061_reference_jobs.up.sql
  datastore/tests/test_updates.py
  sfa_api/aggregates.py
  sfa_api/forecasts.py
  sfa_api/observations.py
  sfa_api/schema.py
  sfa_api/sites.py
  sfa_api/tests/rbac/test_users.py
  sfa_api/tests/test_aggregates.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
  sfa_api/tests/test_schema.py
  sfa_api/tests/test_sites.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_storage_interface.py
Labels: database, enhancement

#290 validate event data uploads
  datastore/migrations/0050_event_write_metadata.down.sql
  datastore/migrations/0050_event_write_metadata.up.sql
  datastore/tests/test_reads.py
  sfa_api/forecasts.py
  sfa_api/observations.py
  sfa_api/tests/test_cdf_forecast.py
  sfa_api/tests/test_forecast.py
  sfa_api/tests/test_observations.py
  sfa_api/utils/request_handling.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_request_handling.py
  sfa_api/utils/tests/test_storage_interface.py
Labels: enhancement

#287 Aggregate values
  datastore/tests/test_updates.py
  sfa_api/aggregates.py
  sfa_api/schema.py
  sfa_api/tests/test_aggregates.py
  sfa_api/utils/tests/test_validators.py
  sfa_api/utils/validators.py
Labels: bug

#295 add endpoint to delete obs from agg
  datastore/migrations/0052_delete_aggregate_observation.down.sql
  datastore/migrations/0052_delete_aggregate_observation.up.sql
  datastore/tests/test_deletes.py
  sfa_api/aggregates.py
  sfa_api/tests/test_aggregates.py
  sfa_api/utils/storage_interface.py
  sfa_api/utils/tests/test_storage_interface.py
Labels: database, enhancement

#297 Convert None to NaN in timeseries before calling compute_aggregate
  sfa_api/tests/test_aggregates.py
  sfa_api/utils/storage_interface.py
Labels: bug
